import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-platform-session","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:CORS});
const text=(v:any)=>String(v??'').trim();
const lower=(v:any)=>text(v).toLowerCase();
const sha256=async(v:string)=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')};
const activeStatus=(v:any)=>!/(revoked|expired|inactive|disabled|blocked|deleted|archived|موقوف|معطل|محذوف)/i.test(text(v||'active'));

async function session(admin:any,raw:string){if(!raw)return null;const hash=await sha256(raw);const q=await admin.from('platform_sessions').select('*').eq('session_token_hash',hash).eq('status','active').limit(1).maybeSingle();if(q.error||!q.data)return null;if(q.data.expires_at&&Date.parse(q.data.expires_at)<Date.now())return null;try{await admin.from('platform_sessions').update({last_seen_at:new Date().toISOString()}).eq('id',q.data.id)}catch(_){}return q.data}

const roleProfile=(role:string)=>{
 const r=lower(role);if(/manager|leadership|principal/.test(r))return{key:'leadership',label:'وكيل القيادة المدرسية',prompt:'ركز على القيادة، الأولويات، المخاطر، الجاهزية، الأداء، الاجتماعات، التكليفات والانضباط.'};
 if(/agent|agency|deputy|wakil/.test(r))return{key:'agency',label:'وكيل العمليات المدرسية',prompt:'ركز على التشغيل والمتابعة والسجلات والتكليفات والانضباط واللجان.'};
 if(/student_advisor|counselor/.test(r))return{key:'student_advisor',label:'وكيل التوجيه الطلابي',prompt:'ركز على التوجيه الطلابي والتدخلات وقياس الأثر مع حماية خصوصية الطلاب.'};
 if(/health/.test(r))return{key:'health_advisor',label:'وكيل التوجيه الصحي',prompt:'ركز على التوجيه الصحي والبرامج والبيئة الصحية دون تقديم تشخيص طبي.'};
 if(/kindergarten/.test(r))return{key:'kindergarten_teacher',label:'وكيل رياض الأطفال',prompt:'ركز على الطفولة المبكرة والخبرات والنمو والشراكة الأسرية. لا تستخدم منطق الاختبارات التقليدية.'};
 if(/activity/.test(r))return{key:'activity_leader',label:'وكيل النشاط المدرسي',prompt:'ركز على البرامج والمبادرات والمشاركة والشواهد وقياس الأثر.'};
 if(/administrative|admin_staff/.test(r))return{key:'administrative_employee',label:'وكيل الموظف الإداري',prompt:'ركز على الخطة والتنفيذ والتقييم والتحسين والتوثيق الإداري.'};
 return{key:'performance',label:'وكيل المعلم والأداء',prompt:'ركز على الأداء الوظيفي والتقارير والسجلات والشواهد والتطوير المهني.'};
};

const LEADERS=new Set(['leadership','agency']);
const allowedTools=(role:string)=>{
  if(role==='leadership')return new Set(['get_current_module_state','get_school_overview','get_readiness_status','get_tasks','get_meetings','get_files','get_performance_status','get_discipline_summary','search_school_records','get_memory','search_regulatory_knowledge','propose_action']);
  if(role==='agency')return new Set(['get_current_module_state','get_school_overview','get_readiness_status','get_tasks','get_meetings','get_files','get_performance_status','get_discipline_summary','search_school_records','get_memory','search_regulatory_knowledge','propose_action']);
  if(role==='student_advisor')return new Set(['get_current_module_state','get_tasks','get_files','search_school_records','get_memory','search_regulatory_knowledge','propose_action']);
  if(role==='health_advisor'||role==='activity_leader'||role==='kindergarten_teacher'||role==='administrative_employee'||role==='performance')return new Set(['get_current_module_state','get_tasks','get_files','get_performance_status','search_school_records','get_memory','search_regulatory_knowledge','propose_action']);
  return new Set(['get_current_module_state','get_tasks','get_files','get_memory','search_regulatory_knowledge','propose_action']);
};
function ownRows(rows:any[],c:any){if(LEADERS.has(c.role))return rows;const uid=String(c.userId||'');return(rows||[]).filter((r:any)=>[r.user_id,r.assignee_id,r.employee_id,r.owner_user_id,r.created_by].some(v=>v&&String(v)===uid));}
function assertToolAllowed(tool:string,c:any){if(!allowedTools(c.role).has(tool))throw new Error('هذه الأداة غير متاحة للدور الحالي.');}

async function safeRows(admin:any,table:string,schoolId:string,extra?:(q:any)=>any,limit=80){try{let q=admin.from(table).select('*').eq('school_id',schoolId).limit(limit);if(extra)q=extra(q);const r=await q;if(r.error)return[];return r.data||[]}catch(_){return[]}}
function compact(rows:any[],fields:string[]=[]){return(rows||[]).slice(0,80).map((r:any)=>{if(!fields.length)return r;const o:any={};fields.forEach(k=>{if(r[k]!==undefined&&r[k]!==null)o[k]=r[k]});return o})}

async function executeTool(admin:any,tool:string,args:any,c:any){assertToolAllowed(tool,c);const sid=c.schoolId,year=c.academicYear;
 if(tool==='search_regulatory_knowledge'){
   const query=text(args?.query);if(!query)return{query:'',sources:[],message:'لم يتم إرسال سؤال للبحث التنظيمي.'};
   const emb=await embedQuery(query);if(!Array.isArray(emb)||!emb.length)return{query,sources:[],message:'تعذر إنشاء تمثيل دلالي للسؤال.'};
   const r=await admin.rpc('match_knowledge_chunks',{query_embedding:vectorLiteral(emb),match_threshold:0.24,match_count:Math.max(1,Math.min(Number(args?.limit||7),10)),category_filter:text(args?.category)||null});
   if(r.error)throw new Error(r.error.message);
   const rows=(r.data||[]).map((x:any)=>({documentId:x.document_id,title:x.title,category:x.category,authority:x.authority,version:x.version_label,pageStart:x.page_start,pageEnd:x.page_end,heading:x.heading,content:x.content,similarity:x.similarity}));
   return{query,sources:rows,instruction:'اعتمد على هذه المصادر عند الإجابة التنظيمية. اذكر اسم الدليل ورقم الصفحة. إذا لم يوجد نص كافٍ فلا تختلق إجراءً رسميًا.'};
 }
 if(tool==='get_current_module_state'){const f=lower(c.page);let module='';if(f.includes('readiness'))module='readiness';else if(f.includes('discipline'))module='discipline';else if(f.includes('meeting'))module='meetings';else if(f.includes('task')||f.includes('assignment'))module='tasks';else if(f.includes('performance'))module='performance';else if(f.includes('student_advisor'))module='student_advisor';else if(f.includes('health'))module='health_advisor';else if(f.includes('kindergarten'))module='kindergarten_teacher';else if(f.includes('activity'))module='activity_leader';else if(f.includes('administrative'))module='administrative_employee';if(!module)return{module:'unknown',state:[]};const rows=await safeRows(admin,'platform_module_state',sid,q=>q.eq('module_key',module),50);return{module,state:ownRows(rows,c)}}
 if(tool==='get_school_overview'){
   const [tasks,meetings,files,readiness,perf,discipline]=await Promise.all([safeRows(admin,'central_tasks',sid,undefined,250),safeRows(admin,'meetings',sid,undefined,120),safeRows(admin,'platform_files',sid,undefined,250),safeRows(admin,'school_readiness_evidence',sid,undefined,250),safeRows(admin,'school_performance_evaluation_states',sid,undefined,120),safeRows(admin,'school_staff_discipline_states',sid,undefined,120)]);
   return{tasks:{total:tasks.length,pending:tasks.filter((x:any)=>!/done|completed|closed|منجز|مكتمل/i.test(text(x.status))).length},meetings:meetings.length,files:files.length,readinessEvidence:readiness.length,performanceStates:perf.length,disciplineStates:discipline.length,academicYear:year};
 }
 if(tool==='get_readiness_status'){const evidence=await safeRows(admin,'school_readiness_evidence',sid,undefined,300);const state=await safeRows(admin,'platform_module_state',sid,q=>q.eq('module_key','readiness'),30);return{evidence:compact(evidence,['id','task_id','phase','status','file_name','created_at','academic_year']),state:compact(state)}}
 if(tool==='get_tasks'){const rows=await safeRows(admin,'central_tasks',sid,undefined,200);return compact(ownRows(rows,c),['id','title','status','priority','assignee_id','assignee_name','due_date','progress','role','module','created_at'])}
 if(tool==='get_meetings'){const rows=await safeRows(admin,'meetings',sid,undefined,120);return compact(rows,['id','title','meeting_date','status','type','location','created_by','created_at'])}
 if(tool==='get_files'){const rows=await safeRows(admin,'platform_files',sid,undefined,180);return compact(ownRows(rows,c),['id','name','file_name','module','role','user_id','academic_year','term','folder_id','created_at'])}
 if(tool==='get_performance_status'){const rows=await safeRows(admin,'school_performance_evaluation_states',sid,undefined,150);return compact(ownRows(rows,c),['id','user_id','role','status','score','year','academic_year','updated_at','created_at'])}
 if(tool==='get_discipline_summary'){const rows=await safeRows(admin,'school_staff_discipline_states',sid,undefined,160);return compact(rows,['id','user_id','employee_id','month','year','academic_year','status','summary','updated_at'])}
 if(tool==='get_memory'){const rows=await safeRows(admin,'agent_memories',sid,q=>q.eq('academic_year',year),120);const visible=rows.filter((x:any)=>x.scope==='school'||String(x.user_id||'')===String(c.userId));return compact(visible,['id','scope','user_id','role','content','tags','created_at'])}
 if(tool==='search_school_records'){
   const query=lower(args?.query);if(!query)return[];const sources=[['central_tasks',['title','status','module','assignee_name']],['meetings',['title','status','type','location']],['platform_files',['name','file_name','module','role']],['platform_module_state',['module_key','state']],['school_readiness_evidence',['task_id','phase','status','file_name']]];const out:any[]=[];
   for(const [table,fields] of sources as any){const rows=ownRows(await safeRows(admin,table,sid,undefined,100),c);for(const r of rows){const hay=lower(fields.map((f:string)=>typeof r[f]==='object'?JSON.stringify(r[f]):r[f]).join(' '));if(hay.includes(query))out.push({source:table,data:compact([r],fields)[0]});if(out.length>=60)break}if(out.length>=60)break}return out;
 }
 if(tool==='propose_action')return{suggestedAction:{type:text(args?.type||'draft'),label:text(args?.label||'إجراء مقترح'),payload:args?.payload||{},risk:/delete|send|approve|archive_year|close_year|permission|role/i.test(text(args?.type))?'red':'yellow'}};
 throw new Error('أداة غير معروفة: '+tool);
}

const tools=[
 {type:'function',name:'get_current_module_state',description:'قراءة الحالة السحابية المهيكلة للقسم المفتوح حاليًا، دون السماح باختيار قسم آخر.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_school_overview',description:'قراءة مؤشرات عامة آمنة للمدرسة الحالية.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_readiness_status',description:'قراءة حالة الجاهزية والشواهد للمدرسة الحالية.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_tasks',description:'قراءة التكليفات والمهام الحالية في المدرسة.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_meetings',description:'قراءة الاجتماعات المسجلة للمدرسة.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_files',description:'قراءة فهرس الملفات والشواهد السحابية للمدرسة الحالية.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_performance_status',description:'قراءة حالات تقييم الأداء الوظيفي المتاحة للدور الحالي.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'get_discipline_summary',description:'قراءة ملخصات الانضباط الوظيفي المتاحة.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'search_school_records',description:'البحث داخل سجلات المدرسة المسموح بها.',parameters:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},strict:true},
 {type:'function',name:'search_regulatory_knowledge',description:'البحث في قاعدة الأدلة التنظيمية والإجرائية الرسمية المركزية. استخدمها لكل سؤال عن لائحة أو دليل أو إجراء أو تنظيم أو صلاحية أو تعميم أو آلية عمل رسمية. يجب ذكر اسم الدليل والصفحة عند الاستناد للنتائج.',parameters:{type:'object',properties:{query:{type:'string'},category:{type:'string'},limit:{type:'integer',minimum:1,maximum:10}},required:['query'],additionalProperties:false},strict:false},
 {type:'function',name:'get_memory',description:'قراءة الذاكرة المؤسسية المقيدة بالمستخدم والمدرسة والعام.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'propose_action',description:'اقتراح إجراء يحتاج مراجعة المستخدم. لا ينفذ التغييرات مباشرة.',parameters:{type:'object',properties:{type:{type:'string'},label:{type:'string'},payload:{type:'object',additionalProperties:true}},required:['type','label','payload'],additionalProperties:false},strict:false}
];

function outputText(data:any){if(data?.output_text)return data.output_text;const parts:any[]=[];for(const item of data?.output||[])if(item.type==='message')for(const c of item.content||[])if(c.type==='output_text'&&c.text)parts.push(c.text);return parts.join('\n')}
async function openai(body:any){
  const gateway=`${Deno.env.get('SUPABASE_URL') || ''}/functions/v1/ASK-AI`;
  if(!body.model||body.model==='gpt-5')body.model='gpt-4.1-mini';
  body.store=false;
  const r=await fetch(gateway,{method:'POST',headers:{'content-type':'application/json','x-agent-source':'school-platform-v2'},body:JSON.stringify({mode:'responses',request:body})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d?.error?.message||d?.error||d?.message||'فشل الاتصال ببوابة الذكاء الاصطناعي المركزية.');
  return d
}
async function embedQuery(input:string){
  const gateway=`${Deno.env.get('SUPABASE_URL') || ''}/functions/v1/ASK-AI`;
  const r=await fetch(gateway,{method:'POST',headers:{'content-type':'application/json','x-agent-source':'school-platform-v2'},body:JSON.stringify({mode:'embeddings',input:[input]})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d?.error?.message||d?.error||d?.message||'تعذر البحث في القاعدة المعرفية.');
  return d?.data?.[0]?.embedding||[];
}
const vectorLiteral=(a:any[])=>'['+(a||[]).map(n=>Number(n).toFixed(8)).join(',')+']';

async function audit(admin:any,c:any,event:string,detail:any,requestId:string){try{await admin.from('agent_audit_log').insert({school_id:c.schoolId,user_id:c.userId,role:c.role,academic_year:c.academicYear,event_type:event,details:detail||{},request_id:requestId})}catch(_){}}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'طريقة الطلب غير مدعومة'},405);const requestId=crypto.randomUUID();try{
 const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({error:'إعدادات Supabase غير مكتملة',requestId},500);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const raw=text(req.headers.get('x-platform-session'));const s=await session(admin,raw);if(!s)return json({error:'جلسة المنصة غير صالحة أو منتهية',code:'SESSION_INVALID',requestId},401);
 const body=await req.json().catch(()=>({})),action=lower(body.action||'chat'),ctx=body.context||{};if(String(ctx.schoolId||'')!==String(s.school_id||''))return json({error:'سياق المدرسة لا يطابق الجلسة السحابية',code:'SCHOOL_CONTEXT_MISMATCH',requestId},403);if(ctx.role&&lower(ctx.role)!==lower(s.role)&&roleProfile(ctx.role).key!==roleProfile(s.role).key)return json({error:'سياق الدور لا يطابق الجلسة السحابية',code:'ROLE_CONTEXT_MISMATCH',requestId},403);
 const c={schoolId:String(s.school_id),userId:String(s.user_id),role:roleProfile(s.role).key,rawRole:s.role,academicYear:text(ctx.academicYear||'1448'),academicYearStatus:text(ctx.academicYearStatus||'active'),membershipId:text(ctx.membershipId),page:text(ctx.file),schoolName:text(ctx.schoolName)};const profile=roleProfile(c.role);const availableTools=tools.filter((t:any)=>allowedTools(c.role).has(t.name));
 if(action==='memory_list'){const r=await admin.from('agent_memories').select('*').eq('school_id',c.schoolId).eq('academic_year',c.academicYear).eq('status','active').order('created_at',{ascending:false}).limit(150);const memories=(r.data||[]).filter((x:any)=>x.scope==='school'||String(x.user_id||'')===String(c.userId));return json({success:true,memories,requestId})}
 if(action==='memory_add'){const content=text(body.payload?.text).slice(0,8000);if(!content)return json({error:'الذاكرة فارغة',requestId},400);let scope=text(body.payload?.scope||'user');if(scope==='school'&&!LEADERS.has(c.role))scope='user';const ins=await admin.from('agent_memories').insert({school_id:c.schoolId,user_id:c.userId,role:c.role,academic_year:c.academicYear,scope,content,tags:body.payload?.tags||[]}).select('*').single();if(ins.error)throw new Error(ins.error.message);await audit(admin,c,'memory.add',{id:ins.data.id,scope},requestId);return json({success:true,memory:ins.data,requestId})}
 if(action==='memory_delete'){const id=text(body.payload?.id);const q=await admin.from('agent_memories').select('*').eq('id',id).eq('school_id',c.schoolId).limit(1).maybeSingle();if(q.error||!q.data)return json({error:'الذاكرة غير موجودة',requestId},404);if(String(q.data.user_id||'')!==String(c.userId)&&!LEADERS.has(c.role))return json({error:'لا تملك صلاحية حذف هذه الذاكرة',requestId},403);await admin.from('agent_memories').update({status:'deleted',updated_at:new Date().toISOString()}).eq('id',id).eq('school_id',c.schoolId);await audit(admin,c,'memory.delete',{id},requestId);return json({success:true,requestId})}
 if(action==='history'){const r=await admin.from('agent_conversations').select('*').eq('school_id',c.schoolId).eq('user_id',c.userId).eq('academic_year',c.academicYear).order('updated_at',{ascending:false}).limit(80);return json({success:true,conversations:r.data||[],requestId})}
 if(action==='history_messages'){const id=text(body.payload?.conversationId);const cq=await admin.from('agent_conversations').select('*').eq('id',id).eq('school_id',c.schoolId).eq('user_id',c.userId).eq('academic_year',c.academicYear).limit(1).maybeSingle();if(cq.error||!cq.data)return json({error:'المحادثة غير موجودة في هذا السياق',requestId},404);const mq=await admin.from('agent_messages').select('*').eq('conversation_id',id).eq('school_id',c.schoolId).eq('user_id',c.userId).order('created_at',{ascending:true}).limit(300);return json({success:true,conversation:cq.data,messages:mq.data||[],requestId})}
 if(action==='tool'){const tool=text(body.payload?.tool),result=await executeTool(admin,tool,body.payload?.args||{},c);await audit(admin,c,'tool.direct',{tool},requestId);return json({success:true,result,answer:JSON.stringify(result,null,2),toolsUsed:[tool],requestId})}
 if(action==='file'){
   const f=body.payload?.file;if(!f?.base64)return json({error:'لم يتم إرسال ملف صالح',requestId},400);const prompt=text(body.payload?.prompt||'حلل الملف في سياق العمل المدرسي الحالي.');const system=`أنت ${profile.label} داخل منصة إدارة مدرسية سعودية. ${profile.prompt} المدرسة الحالية فقط: ${c.schoolId}. العام: ${c.academicYear}هـ. حلل الملف دون اختلاق بيانات، وميز الحقائق عن التوصيات.`;const input=[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:prompt},{type:'input_file',filename:text(f.name||'file'),file_data:`data:${text(f.type||'application/octet-stream')};base64,${f.base64}`}]}];const d=await openai({model:Deno.env.get('OPENAI_AGENT_MODEL')||'gpt-4.1-mini',input,store:false});const answer=outputText(d);await audit(admin,c,'file.analysis',{fileName:f.name},requestId);return json({success:true,answer,toolsUsed:[],requestId})
 }
 if(action==='brief'){
   let overview:any,metrics:any[],used:string[];
   if(LEADERS.has(c.role)){overview=await executeTool(admin,'get_school_overview',{},c);metrics=[{label:'المهام',value:overview.tasks.total,note:`المعلقة: ${overview.tasks.pending}`},{label:'الاجتماعات',value:overview.meetings,note:'المسجلة'},{label:'الملفات',value:overview.files,note:'في الفهرس السحابي'},{label:'شواهد الجاهزية',value:overview.readinessEvidence,note:`العام ${c.academicYear}هـ`}];used=['get_school_overview'];}
   else{const parts:any[]=await Promise.all([executeTool(admin,'get_tasks',{},c),executeTool(admin,'get_files',{},c),executeTool(admin,'get_current_module_state',{},c)]);const tasks:any[]=Array.isArray(parts[0])?parts[0]:[],files:any[]=Array.isArray(parts[1])?parts[1]:[],moduleState:any=parts[2]||{};overview={myTasks:tasks,myFiles:files,currentModule:moduleState};metrics=[{label:'مهامي',value:tasks.length,note:'في المدرسة الحالية'},{label:'ملفاتي',value:files.length,note:'في الفهرس السحابي'},{label:'القسم',value:moduleState.module||'الحالي',note:`العام ${c.academicYear}هـ`}];used=['get_tasks','get_files','get_current_module_state'];}
   const d=await openai({model:Deno.env.get('OPENAI_AGENT_MODEL')||'gpt-4.1-mini',store:false,input:`أنت ${profile.label}. ${profile.prompt}\nهذه البيانات الفعلية المسموح بها للدور: ${JSON.stringify(overview).slice(0,16000)}\nأنشئ موجزًا تنفيذيًا عربيًا قصيرًا من 4 إلى 5 نقاط، وحدد ما يستحق الانتباه دون افتراض بيانات غير موجودة.`});const answer=outputText(d);await audit(admin,c,'brief',{tools:used},requestId);return json({success:true,answer,metrics,suggestions:[],toolsUsed:used,requestId})
 }
 const page=body.client?.page||{},memory=body.client?.memory||[],conversation=body.payload?.conversation||[],message=text(body.payload?.message||'حلل السياق الحالي.');const developer=`أنت ${profile.label}، وكيل تشغيلي داخل منصة إدارة مدرسية سعودية. ${profile.prompt}\nقواعد إلزامية:\n1) لا تستخدم إلا بيانات المدرسة الحالية ${c.schoolId} والعام ${c.academicYear}هـ والدور ${c.role}.\n2) استخدم الأدوات عندما تتطلب الإجابة حقيقة من النظام؛ لا تخمن السجلات أو الأعداد.\n3) عمليات التغيير لا تنفذها مباشرة: استخدم propose_action لإرسال اقتراح للمستخدم.\n4) اذكر بوضوح عندما تكون البيانات غير متاحة.\n5) احم البيانات الحساسة ولا تعرض رموز الجلسات أو الأسرار.\n6) اجعل الإجابة عملية ومختصرة، واستخدم اللغة العربية.\n7) عند اقتراح تعبئة حقول استخدم propose_action بالنوع fill_fields وبحمولة {fields:[{id,value}]} مستندًا إلى معرفات الحقول الحالية فقط.\n8) عند طلب المدير/الوكيل إنشاء تكليف وبعد توفر المكلف، استخدم propose_action بالنوع create_task_draft وبحمولة متوافقة مع محرك التكليفات: {title,description,assignedTo,assigneeEmail,assigneeName,assigneeRole,priority,dueDate,moduleKey}. لا تنفذه بنفسك.\n9) لا تقترح حذفًا أو اعتمادًا نهائيًا إذا لم يطلب المستخدم ذلك صراحة.\n10) حالة العام الدراسي: ${c.academicYearStatus}. إذا كانت archived فتعامل مع البيانات للقراءة والتحليل فقط ولا تقترح أي إجراء كتابي.\nالصفحة الحالية: ${c.page}.\nالنص الظاهر المختصر: ${text(page.text).slice(0,9000)}\nالحقول الحالية ومعرفاتها: ${JSON.stringify(page.fields||[]).slice(0,9000)}\nالذاكرة المسموح بها: ${JSON.stringify(memory).slice(0,6000)}\nملخص البيانات المحلية المقيدة بالسياق: ${JSON.stringify(body.client?.localSummary||{}).slice(0,7000)}`;
 const transcript=conversation.slice(-14).map((m:any)=>`${m.role==='assistant'?'الوكيل':'المستخدم'}: ${text(m.content).slice(0,7000)}`).join('\n\n');let input:any[]=[{role:'developer',content:[{type:'input_text',text:developer}]},{role:'user',content:[{type:'input_text',text:(transcript?`سجل المحادثة السابقة:\n${transcript}\n\n`:'')+`الطلب الحالي:\n${message}`}]}];let workingInput:any[]=[...input];let d=await openai({model:Deno.env.get('OPENAI_AGENT_MODEL')||'gpt-4.1-mini',input:workingInput,tools:availableTools,tool_choice:'auto',parallel_tool_calls:false,store:false});const toolsUsed:string[]=[],suggestedActions:any[]=[],sourceRefs:any[]=[];
 for(let round=0;round<6;round++){const calls=(d.output||[]).filter((x:any)=>x.type==='function_call');if(!calls.length)break;const outputs:any[]=[];for(const call of calls){let args={};try{args=JSON.parse(call.arguments||'{}')}catch(_){};let result:any;try{result=await executeTool(admin,call.name,args,c);toolsUsed.push(call.name);if(result?.suggestedAction)suggestedActions.push(result.suggestedAction);if(call.name==='search_regulatory_knowledge'&&Array.isArray(result?.sources))sourceRefs.push(...result.sources)}catch(e){result={error:e instanceof Error?e.message:String(e)}}outputs.push({type:'function_call_output',call_id:call.call_id,output:JSON.stringify(result)})}workingInput=[...workingInput,...(d.output||[]),...outputs];d=await openai({model:Deno.env.get('OPENAI_AGENT_MODEL')||'gpt-4.1-mini',input:workingInput,tools:availableTools,tool_choice:'auto',parallel_tool_calls:false,store:false})}
 const answer=outputText(d)||'لم يُنتج الوكيل إجابة نصية.';
 const convId=text(body.payload?.conversationId);if(convId&&/^[0-9a-f-]{36}$/i.test(convId)){try{const cq=await admin.from('agent_conversations').select('id,school_id,user_id').eq('id',convId).limit(1).maybeSingle();if(cq.data){if(String(cq.data.school_id)===String(c.schoolId)&&String(cq.data.user_id||'')===String(c.userId))await admin.from('agent_conversations').update({title:text(body.payload?.title||message).slice(0,160),role:c.role,academic_year:c.academicYear,updated_at:new Date().toISOString()}).eq('id',convId).eq('school_id',c.schoolId).eq('user_id',c.userId);else throw new Error('conversation_scope_mismatch')}else{await admin.from('agent_conversations').insert({id:convId,school_id:c.schoolId,user_id:c.userId,role:c.role,academic_year:c.academicYear,title:text(body.payload?.title||message).slice(0,160),status:'active'})}await admin.from('agent_messages').insert([{conversation_id:convId,school_id:c.schoolId,user_id:c.userId,role:'user',content:message,tools_used:[]},{conversation_id:convId,school_id:c.schoolId,user_id:c.userId,role:'assistant',content:answer,tools_used:toolsUsed}])}catch(_){} }
 await audit(admin,c,'chat',{toolsUsed,message:message.slice(0,300)},requestId);return json({success:true,answer,toolsUsed,sources:sourceRefs.slice(0,10),suggestedActions,requestId});
 }catch(e){console.error('[platform-agent]',requestId,e);return json({error:e instanceof Error?e.message:String(e),requestId},500)}});
