import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(v:any,n=20000)=>String(v??'').trim().slice(0,n);const isUuid=(v:any)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
async function meta(db:any,id:string){try{const r=await db.auth.admin.getUserById(id);const u=r.data?.user;return {email:u?.email||'',name:u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email||''}}catch(_){return {email:'',name:''}}}
const roleLabel=(r:string)=>({owner:'مالك',manager:'مدير/ة المدرسة',agent:'وكيل/ة',teacher:'معلم/ة',student_advisor:'موجه/ة طلابي/ة',health_advisor:'موجه/ة صحي/ة',activity_leader:'رائد/ة النشاط',kindergarten_teacher:'معلمة رياض أطفال',administrative_employee:'موظف/ة إداري/ة'} as any)[r]||r;
async function shaBytes(v:Uint8Array){const d=await crypto.subtle.digest('SHA-256',v);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function decodeSignature(data:any){const x=String(data||'');const m=x.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/i);if(!m)throw new Error('صيغة التوقيع غير صالحة');if(m[2].length>2800000)throw new Error('حجم صورة التوقيع كبير جدًا');const raw=atob(m[2]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const ext=m[1].toLowerCase()==='jpeg'?'jpg':m[1].toLowerCase();return {bytes,mime:'image/'+m[1].toLowerCase(),ext}}
function allowedDirectTarget(sender:string,target:string){if(sender==='owner')return target==='manager';if(sender==='manager')return target!=='manager';if(sender==='agent')return target!=='owner';return target==='agent'}
function allowedBulkTarget(sender:string,target:string){if(sender==='manager')return !['owner','manager'].includes(target);if(sender==='agent')return target!=='owner';return false}
function groupAllowed(sender:string){return sender==='manager'||sender==='agent'}
function allAllowed(sender:string){return sender==='manager'||sender==='agent'}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 const db=createClient(url,service,{auth:{persistSession:false}}),b=await req.json().catch(()=>({})),sid=clean(b.schoolId,80),action=clean(b.action,80),actor=clean(b.actorRole,80);if(!sid)return json({error:'school_required'},400);
 const sq=await db.from('schools').select('id,status').eq('id',sid).maybeSingle();if(sq.error)throw sq.error;if(!sq.data||sq.data.status!=='active')return json({error:'school_not_active'},403);
 const mq=await db.from('school_members').select('id,user_id,role,status,display_name').eq('school_id',sid).eq('user_id',user.id).eq('status','active');if(mq.error)throw mq.error;const roles=(mq.data||[]).map((x:any)=>String(x.role));const role=actor&&roles.includes(actor)?actor:roles[0];if(!role)return json({error:'forbidden'},403);
 const currentMember=(mq.data||[]).find((x:any)=>String(x.role)===role)||(mq.data||[])[0];
 async function allMembers(){const r=await db.from('school_members').select('id,user_id,role,status,display_name').eq('school_id',sid).eq('status','active');if(r.error)throw r.error;const out=[];for(const m of r.data||[]){const x=await meta(db,m.user_id);out.push({id:m.user_id,user_id:m.user_id,email:x.email,full_name:m.display_name||x.name||x.email||'',role:m.role,status:m.status})}return out}
 async function canReadMessage(id:string){const m=await db.from('internal_messages').select('*').eq('id',id).eq('school_id',sid).maybeSingle();if(m.error)throw m.error;if(!m.data)return {m:null,r:null};const rr=await db.from('internal_message_recipients').select('*').eq('message_id',id).eq('school_id',sid).eq('recipient_user_id',user.id).maybeSingle();if(rr.error)throw rr.error;return {m:m.data,r:rr.data}}
 if(action==='users'||action==='contacts'){
   const members=await allMembers();const visible=members.filter((x:any)=>x.id!==user.id&&allowedDirectTarget(role,String(x.role)));const bulkVisible=members.filter((x:any)=>x.id!==user.id&&allowedBulkTarget(role,String(x.role)));
   if(action==='contacts')return json({ok:true,contacts:visible.map((x:any)=>({user_id:x.id,role:x.role,email:x.email,label:`${x.full_name||x.email} — ${roleLabel(x.role)}`})),policy:role==='owner'?'مراسلات المالك مخصصة لمدير/مديرة المدرسة فقط.':role==='manager'?'يمكن للمدير مراسلة المالك مباشرة، ومراسلة منسوبي المدرسة فرديًا أو جماعيًا.':role==='agent'?'يمكن للوكيل مراسلة المدير وجميع المستخدمين فرديًا أو جماعيًا.':'يمكن للمستخدم مراسلة الوكلاء فقط.'});
   const counts:any={};bulkVisible.forEach((u:any)=>counts[u.role]=(counts[u.role]||0)+1);return json({ok:true,users:visible,roleCounts:counts,current:{id:user.id,role,email:user.email||'',full_name:currentMember?.display_name||''},permissions:{groupSend:groupAllowed(role),allSchool:allAllowed(role),official:['owner','manager','agent'].includes(role),convertTask:['manager','agent'].includes(role)}})
 }
 if(action==='send'){
   const members=await allMembers(),direct=(Array.isArray(b.recipientIds)?b.recipientIds:[]).map(String),groups=(Array.isArray(b.recipientRoles)?b.recipientRoles:[]).map(String),all=!!b.allSchool;
   if((groups.length||all)&&!groupAllowed(role))return json({error:'الإرسال الجماعي متاح للمدير والوكيل فقط'},403);if(all&&!allAllowed(role))return json({error:'الإرسال لجميع المستخدمين غير مسموح لهذا الدور'},403);
   let targets=members.filter((x:any)=>{if(x.id===user.id)return false;const targetRole=String(x.role),isDirect=direct.includes(String(x.id))&&allowedDirectTarget(role,targetRole),isGroup=groups.includes(targetRole)&&allowedBulkTarget(role,targetRole),isAll=all&&allowedBulkTarget(role,targetRole);return isDirect||isGroup||isAll});targets=[...new Map(targets.map((x:any)=>[String(x.id),x])).values()];
   if(!targets.length)return json({error:'لم يتم العثور على مستلمين مسموح بهم داخل المدرسة'},400);const subject=clean(b.subject,300),body=clean(b.body,20000);if(!subject||!body)return json({error:'العنوان ونص الرسالة مطلوبان'},400);
   const mid=crypto.randomUUID(),thread=isUuid(b.threadId)?String(b.threadId):mid,type=['message','official','notice','action_request'].includes(String(b.messageType))?String(b.messageType):'message';let ack=['none','read_receipt','signature'].includes(String(b.acknowledgementMode))?String(b.acknowledgementMode):'none';if(type==='official'&&ack==='none')ack='signature';
   const ins=await db.from('internal_messages').insert({id:mid,school_id:sid,sender_id:user.id,sender_user_id:user.id,sender_name:currentMember?.display_name||user.user_metadata?.full_name||user.email||'',sender_role:role,subject,body,priority:['important','urgent'].includes(String(b.priority))?String(b.priority):'normal',message_type:type,require_ack:ack==='signature',acknowledgement_mode:ack,due_at:b.dueAt||null,thread_id:thread,parent_message_id:isUuid(b.parentMessageId)?b.parentMessageId:null,linked_module:clean(b.linked?.module,120)||null,linked_record_type:clean(b.linked?.recordType,120)||null,linked_record_id:clean(b.linked?.recordId,240)||null,linked_title:clean(b.linked?.title,500)||null,linked_url:clean(b.linked?.url,1200)||null,metadata:b.metadata||{}});if(ins.error)throw ins.error;
   const recs=targets.map((x:any)=>({school_id:sid,message_id:mid,recipient_id:x.id,recipient_user_id:x.id,recipient_email:x.email||null,recipient_name:x.full_name||x.email||'',recipient_role:x.role}));const rec=await db.from('internal_message_recipients').insert(recs);if(rec.error){await db.from('internal_messages').delete().eq('id',mid);throw rec.error}
   const att=Array.isArray(b.attachments)?b.attachments.slice(0,15):[];if(att.length){const ids=att.map((a:any)=>clean(a.fileId,80)).filter(isUuid);if(ids.length){const fs=await db.from('platform_files').select('id,school_id,display_name,original_name,mime_type,file_size,status').eq('school_id',sid).in('id',ids);if(fs.error)throw fs.error;const fmap=new Map((fs.data||[]).filter((f:any)=>f.status==='active').map((f:any)=>[String(f.id),f]));const rows=[];for(const a of att){const f:any=fmap.get(String(a.fileId));if(!f)continue;rows.push({school_id:sid,message_id:mid,file_id:f.id,file_name:f.display_name||f.original_name||'مرفق',mime_type:f.mime_type||null,file_size:Number(f.file_size||0),source:a.source==='library'?'library':'device'})}if(rows.length){const ia=await db.from('internal_message_attachments').insert(rows);if(ia.error)throw ia.error}}}
   return json({ok:true,messageId:mid,recipientCount:recs.length})
 }
 if(['inbox','list','archive','pinned'].includes(action)){
   let q=db.from('internal_message_recipients').select('*,message:internal_messages(*)').eq('school_id',sid).eq('recipient_user_id',user.id);if(action==='archive'||b.box==='archive')q=q.not('archived_at','is',null);else q=q.is('archived_at',null);if(action==='pinned'||b.box==='pinned')q=q.not('pinned_at','is',null);const r=await q.order('pinned_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(150);if(r.error)throw r.error;const rows=r.data||[];return json({ok:true,messages:rows.map((x:any)=>({...x.message,read_at:x.read_at,acknowledged_at:x.acknowledged_at,action_status:x.action_status,pinned_at:x.pinned_at,recipient_archived_at:x.archived_at})),unread:rows.filter((x:any)=>!x.read_at).length})
 }
 if(action==='sent'){
   const r=await db.from('internal_messages').select('*,internal_message_recipients(*)').eq('school_id',sid).eq('sender_user_id',user.id).order('created_at',{ascending:false}).limit(150);if(r.error)throw r.error;return json({ok:true,messages:(r.data||[]).map((m:any)=>{const rr=m.internal_message_recipients||[];return {...m,read_count:rr.filter((x:any)=>x.read_at).length,ack_count:rr.filter((x:any)=>x.acknowledged_at||x.signed_at).length,recipient_count:rr.length}})})
 }
 if(action==='stats'){
   const [mine,sent]=await Promise.all([db.from('internal_message_recipients').select('read_at,archived_at,pinned_at').eq('school_id',sid).eq('recipient_user_id',user.id),db.from('internal_messages').select('id').eq('school_id',sid).eq('sender_user_id',user.id)]);if(mine.error)throw mine.error;if(sent.error)throw sent.error;const a=mine.data||[];return json({ok:true,inbox:a.filter((x:any)=>!x.archived_at).length,unread:a.filter((x:any)=>!x.archived_at&&!x.read_at).length,pinned:a.filter((x:any)=>!x.archived_at&&x.pinned_at).length,archive:a.filter((x:any)=>x.archived_at).length,sent:(sent.data||[]).length})
 }
 if(action==='read'){
   const id=clean(b.messageId,80);const {m,r}=await canReadMessage(id);if(!m||(!r&&String(m.sender_user_id)!==user.id))return json({error:'not_found'},404);let rr=r;if(rr&&!rr.read_at){const at=new Date().toISOString();const up=await db.from('internal_message_recipients').update({read_at:at}).eq('id',rr.id).select('*').single();if(up.error)throw up.error;rr=up.data}const rec=await db.from('internal_message_recipients').select('*').eq('school_id',sid).eq('message_id',id);if(rec.error)throw rec.error;const atts=await db.from('internal_message_attachments').select('*').eq('school_id',sid).eq('message_id',id).order('created_at');if(atts.error)throw atts.error;const thread=await db.from('internal_messages').select('*').eq('school_id',sid).eq('thread_id',m.thread_id||m.id).order('created_at');if(thread.error)throw thread.error;return json({ok:true,message:m,recipientState:rr,recipients:rec.data||[],attachments:atts.data||[],thread:thread.data||[]})
 }
 if(['archive-message','unarchive-message','pin','unpin','mark-unread','action-status','acknowledge'].includes(action)){
   const {m,r}=await canReadMessage(clean(b.messageId,80));if(!m||!r)return json({error:'الإجراء متاح للمستلم فقط'},403);const patch:any={};if(action==='archive-message')patch.archived_at=new Date().toISOString();if(action==='unarchive-message')patch.archived_at=null;if(action==='pin')patch.pinned_at=new Date().toISOString();if(action==='unpin')patch.pinned_at=null;if(action==='mark-unread')patch.read_at=null;if(action==='action-status'){patch.action_status=['accepted','in_progress','done','declined'].includes(String(b.status))?String(b.status):'none';patch.action_note=clean(b.note,1000)||null}if(action==='acknowledge'){const sig=decodeSignature(b.signatureData);const at=new Date().toISOString(),path=`internal-message-signatures/${sid}/${m.id}/${r.id}-${crypto.randomUUID()}.${sig.ext}`;const upSig=await db.storage.from('private-school-files').upload(path,sig.bytes,{contentType:sig.mime,upsert:false,cacheControl:'31536000'});if(upSig.error)throw upSig.error;patch.acknowledged_at=at;patch.signed_at=at;patch.read_at=r.read_at||at;patch.signature_storage_path=path;patch.signature_mime_type=sig.mime;patch.signature_hash=await shaBytes(sig.bytes);patch.acknowledgement_metadata={signed_via:'saved_digital_signature',signed_at:at}}const up=await db.from('internal_message_recipients').update(patch).eq('id',r.id).select('*').single();if(up.error)throw up.error;return json({ok:true,state:up.data})
 }
 if(action==='ack-register'){
   const id=clean(b.messageId,80);const m=await db.from('internal_messages').select('*').eq('school_id',sid).eq('id',id).maybeSingle();if(m.error)throw m.error;if(!m.data)return json({error:'not_found'},404);if(String(m.data.sender_user_id)!==user.id&&!['manager','agent'].includes(role))return json({error:'forbidden'},403);const r=await db.from('internal_message_recipients').select('*').eq('school_id',sid).eq('message_id',id).order('recipient_name');if(r.error)throw r.error;const rows=[];for(const x of r.data||[]){let signature_url='';if(x.signature_storage_path){const su=await db.storage.from('private-school-files').createSignedUrl(x.signature_storage_path,300);signature_url=su.data?.signedUrl||''}rows.push({...x,signature_url})}return json({ok:true,message:m.data,recipients:rows,summary:{total:rows.length,read:rows.filter((x:any)=>x.read_at).length,signed:rows.filter((x:any)=>x.signed_at||x.acknowledged_at).length}})
 }
 if(action==='mark-converted'){if(!['manager','agent'].includes(role))return json({error:'forbidden'},403);const up=await db.from('internal_messages').update({converted_task_id:clean(b.taskId,80)}).eq('school_id',sid).eq('id',clean(b.messageId,80));if(up.error)throw up.error;return json({ok:true})}
 return json({error:'unsupported_action'},400)
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
