import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8'}});
const clean=(v:any)=>String(v??'').trim();
const requirements=[
['01','الترخيص التشغيلي','يرفع المالك نسخة الترخيص التشغيلي الساري.',true,false],['02','شهادات السلامة','شهادة سلامة سارية للمبنى والمنشأة.',true,false],['03','رخصة بلدي','رخصة بلدي السارية للمنشأة.',true,false],['04','رخصة البناء','الرخصة أو المستند النظامي للمبنى.',true,true],['05','السجل التجاري','السجل التجاري الساري.',true,false],['06','بيانات المركز السعودي للأعمال','ما يثبت بيانات المنشأة النظامية.',true,true],['07','التكليف الداخلي لمدير المدرسة','قرار أو تكليف مدير/مديرة المدرسة.',false,false],['08','عقد مدير المدرسة من قوى','العقد أو ما يثبت العلاقة التعاقدية.',true,true],['09','بيانات المدير في منصة مدارس','مطابقة بيانات المدير/ة في الأنظمة المعتمدة.',false,false],['10','المسح الأمني','المتطلبات الأمنية متى كانت مطلوبة.',true,true],['11','إعلان الرسوم','اعتماد وإعلان الرسوم الدراسية وفق المتطلبات.',true,false],['12','التقويم الدراسي','التقويم الدراسي المعتمد للمدرسة.',false,false],['13','الطاقة الاستيعابية','توثيق الطاقة الاستيعابية المعتمدة.',false,false],['14','تسجيل المعلمين','اكتمال تسجيل الهيئة التعليمية.',false,false],['15','تسجيل الطلاب','اكتمال تسجيل الطلاب وفق الطاقة الاستيعابية.',false,false],['16','إجراءات الزي المدرسي','توثيق الإجراءات والضوابط الخاصة بالزي.',false,true],['17','ختم الكتب','توثيق إجراءات ختم الكتب عند انطباقها.',false,true],['18','بيان تسليم الكتب','بيان أو سجل تسليم الكتب للطلاب.',false,false],['19','اعتماد الخطة الدراسية','الخطة الدراسية المعتمدة للمدرسة.',false,false]
];
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 const db=createClient(url,service,{auth:{persistSession:false}}),b=await req.json().catch(()=>({})),sid=clean(b.schoolId),action=clean(b.action);if(!sid)return json({error:'school_required'},400);
 const sq=await db.from('schools').select('status').eq('id',sid).maybeSingle();if(sq.error)throw sq.error;if(sq.data?.status!=='active')return json({error:'school_not_active'},403);
 const mq=await db.from('school_members').select('role').eq('school_id',sid).eq('user_id',user.id).eq('status','active');if(mq.error)throw mq.error;const roles=(mq.data||[]).map((x:any)=>String(x.role));const isOwner=roles.includes('owner'),isManager=roles.includes('manager');if(!isOwner&&!isManager)return json({error:'forbidden'},403);
 if(action==='list'){const r=await db.from('compliance_inspections').select('*').eq('school_id',sid).order('created_at',{ascending:false});if(r.error)throw r.error;return json({ok:true,inspections:r.data||[]})}
 if(action==='create'){
   const year=Number(b.academicYear||0);if(year<1448||year>1548)return json({error:'academic_year_out_of_range'},400);const title=`فحص الالتزام ${year}هـ`;
   let ins:any;const existing=await db.from('compliance_inspections').select('*').eq('school_id',sid).eq('academic_year',String(year)).maybeSingle();if(existing.error)throw existing.error;if(existing.data)ins={data:existing.data,error:null};else ins=await db.from('compliance_inspections').insert({school_id:sid,academic_year:String(year),title,status:'in_progress',created_by:user.id,updated_at:new Date().toISOString()}).select('*').single();if(ins.error)throw ins.error;
   const exists=await db.from('compliance_items').select('id').eq('inspection_id',ins.data.id).limit(1);if(exists.error)throw exists.error;if(!(exists.data||[]).length){const rows=requirements.map((x:any,i)=>({inspection_id:ins.data.id,requirement_key:x[0],requirement_order:i+1,title:x[1],requirement_note:x[2],owner_only:x[3],is_conditional:x[4],state:'waiting_evidence'}));const ir=await db.from('compliance_items').insert(rows);if(ir.error)throw ir.error}
   return json({ok:true,inspection:ins.data})
 }
 const iid=clean(b.inspectionId);if(!iid)return json({error:'inspection_required'},400);const iq=await db.from('compliance_inspections').select('*').eq('id',iid).eq('school_id',sid).maybeSingle();if(iq.error)throw iq.error;if(!iq.data)return json({error:'not_found'},404);
 if(action==='get'){
   const items=await db.from('compliance_items').select('*').eq('inspection_id',iid).order('requirement_order');if(items.error)throw items.error;const ids=(items.data||[]).map((x:any)=>x.id);
   let evidenceRows:any[]=[];if(ids.length){const ev=await db.from('compliance_evidence').select('*').eq('school_id',sid).in('item_id',ids);if(ev.error)throw ev.error;evidenceRows=ev.data||[]}
   const fileIds=[...new Set(evidenceRows.map((x:any)=>x.file_id).filter(Boolean))];let files:any[]=[];if(fileIds.length){const fq=await db.from('platform_files').select('id,display_name,original_name,mime_type,file_size,bucket,object_path').eq('school_id',sid).in('id',fileIds);if(fq.error)throw fq.error;files=fq.data||[]}
   const fileMap=new Map(files.map((f:any)=>[f.id,f]));const tp=await db.from('school_template_profiles').select('profile').eq('school_id',sid).maybeSingle();if(tp.error)throw tp.error;
   const mapped=(items.data||[]).map((x:any)=>({...x,item_title:x.title,fulfillment_status:x.state==='complete'?'complete':'pending'}));const completed=mapped.filter((x:any)=>x.fulfillment_status==='complete').length,notApplicable=0,pending=mapped.filter((x:any)=>x.fulfillment_status==='pending').length;
   const evidence=evidenceRows.map((x:any)=>{const f:any=fileMap.get(x.file_id)||{};return {...x,platform_file_id:x.file_id,file_name:f.display_name||f.original_name||'',mime_type:f.mime_type||'',file_size:f.file_size||0}});
   return json({ok:true,inspection:iq.data,items:mapped,evidence,summary:{total:mapped.length,completed,notApplicable,pending,evidenceCount:evidence.length,progress:mapped.length?Math.round(completed/mapped.length*100):0},template:tp.data?.profile||{}})
 }
 if(iq.data.status==='completed')return json({error:'inspection_locked'},409);
 const itemId=clean(b.itemId);let item:any=null;if(itemId){const it=await db.from('compliance_items').select('*').eq('id',itemId).eq('inspection_id',iid).maybeSingle();if(it.error)throw it.error;item=it.data;if(!item)return json({error:'item_not_found'},404);if(item.owner_only&&!isOwner)return json({error:'owner_only_requirement'},403)}
 if(action==='set_requirement_status'){const status=clean(b.status),state=status==='complete'?'complete':'waiting_evidence';if(!['complete','waiting_evidence'].includes(state))return json({error:'invalid_status'},400);const up=await db.from('compliance_items').update({state,notes:clean(b.note)||null}).eq('id',itemId).eq('inspection_id',iid).select('*').single();if(up.error)throw up.error;return json({ok:true,item:{...up.data,fulfillment_status:status}})}
 if(action==='link_evidence'){const file=clean(b.fileId);const fq=await db.from('platform_files').select('id,mime_type').eq('id',file).eq('school_id',sid).maybeSingle();if(!fq.data)return json({error:'invalid_file'},400);const mime=clean(fq.data.mime_type).toLowerCase();if(!(mime==='application/pdf'||mime.startsWith('image/')))return json({error:'unsupported_evidence_type'},400);const ins=await db.from('compliance_evidence').insert({school_id:sid,item_id:itemId,file_id:file,uploaded_by:user.id}).select('*').single();if(ins.error)throw ins.error;await db.from('compliance_items').update({state:'complete'}).eq('id',itemId).eq('inspection_id',iid);return json({ok:true,evidence:{...ins.data,platform_file_id:file}})}
 if(action==='remove_evidence'){const id=clean(b.evidenceId),e=await db.from('compliance_evidence').select('id,item_id').eq('id',id).eq('school_id',sid).maybeSingle();if(e.error)throw e.error;if(!e.data)return json({error:'not_found'},404);const it=await db.from('compliance_items').select('owner_only,inspection_id').eq('id',e.data.item_id).maybeSingle();if(it.error)throw it.error;if(it.data?.inspection_id!==iid)return json({error:'not_found'},404);if(it.data?.owner_only&&!isOwner)return json({error:'owner_only_requirement'},403);await db.from('compliance_evidence').delete().eq('id',id).eq('school_id',sid);const left=await db.from('compliance_evidence').select('id').eq('item_id',e.data.item_id);if(!(left.data||[]).length)await db.from('compliance_items').update({state:'waiting_evidence'}).eq('id',e.data.item_id);return json({ok:true})}
 if(action==='finalize'||action==='complete'){const items=await db.from('compliance_items').select('state').eq('inspection_id',iid);if(items.error)throw items.error;if((items.data||[]).some((x:any)=>x.state!=='complete'))return json({error:'requirements_incomplete'},409);const up=await db.from('compliance_inspections').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',iid).eq('school_id',sid).select('*').single();if(up.error)throw up.error;return json({ok:true,inspection:up.data})}
 return json({error:'unsupported_action'},400)
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
