import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(v:any,n=4000)=>String(v??'').trim().slice(0,n), now=()=>new Date().toISOString();
const REQUEST_TYPES=new Set(['absence','permission','leave']);
const STAFF_ROLES=new Set(['agent','teacher','student_advisor','activity_leader','kindergarten_teacher','health_advisor','administrative_employee']);
const movementType=(t:string)=>t==='absence'?'غياب بعذر':t==='permission'?'استئذان':'إجازة';
async function userMeta(db:any,id:string){try{const r=await db.auth.admin.getUserById(id);const u=r.data?.user;return {email:u?.email||'',name:u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email||''}}catch(_){return {email:'',name:''}}}
async function event(db:any,row:any,actorId:string|null,actorRole:string,eventType:string,note:string|null,snapshot:any={}){const r=await db.from('employee_request_events').insert({school_id:row.school_id,request_id:row.id,actor_id:actorId,actor_role:actorRole||null,event_type:eventType,note:note||null,snapshot});if(r.error)throw r.error}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 const db=createClient(url,service,{auth:{persistSession:false}}),b=await req.json().catch(()=>({})),sid=clean(b.schoolId,80),action=clean(b.action,80),actor=clean(b.actorRole,80);if(!sid)return json({error:'school_required'},400);
 const school=await db.from('schools').select('id,status').eq('id',sid).maybeSingle();if(school.error)throw school.error;if(school.data?.status!=='active')return json({error:'school_not_active'},403);
 const mq=await db.from('school_members').select('id,user_id,role,role_variant,status,supervisor_user_id,supervisor_role,display_name').eq('school_id',sid).eq('user_id',user.id).eq('status','active');if(mq.error)throw mq.error;const memberships=mq.data||[],roles=memberships.map((x:any)=>String(x.role)),role=actor&&roles.includes(actor)?actor:roles[0];if(!role)return json({error:'forbidden'},403);const mine:any=memberships.find((x:any)=>String(x.role)===role)||memberships[0];
 const managerId=async()=>{const r=await db.from('school_members').select('user_id').eq('school_id',sid).eq('role','manager').eq('status','active').limit(1).maybeSingle();if(r.error)throw r.error;return r.data?.user_id||null};
 const agentId=async()=>{if(mine?.supervisor_role==='agent'&&mine?.supervisor_user_id){const s=await db.from('school_members').select('user_id').eq('school_id',sid).eq('user_id',mine.supervisor_user_id).eq('role','agent').eq('status','active').maybeSingle();if(s.data)return s.data.user_id}
   const r=await db.from('school_members').select('user_id,role_variant,created_at').eq('school_id',sid).eq('role','agent').eq('status','active').order('created_at');if(r.error)throw r.error;const a=r.data||[];return (a.find((x:any)=>x.role_variant==='school_affairs')||a[0])?.user_id||null};
 const enrich=async(rows:any[])=>{const out=[];for(const x of rows){const u=await userMeta(db,x.requester_id);out.push({...x,requester_name:u.name,requester_email:u.email})}return out};
 if(action==='context'){
   const [myr,all,perf]=await Promise.all([db.from('employee_requests').select('id,status').eq('school_id',sid).eq('requester_id',user.id),db.from('employee_requests').select('id,status,current_approver').eq('school_id',sid),db.from('performance_report_approvals').select('id,status').eq('school_id',sid).eq('subject_user_id',user.id)]);if(myr.error||all.error||perf.error)throw myr.error||all.error||perf.error;const rows=all.data||[];
   return json({ok:true,role,counts:{myRequests:(myr.data||[]).length,myPerformance:(perf.data||[]).length,agentPending:rows.filter((x:any)=>x.status==='pending_agent'&&x.current_approver===user.id).length,managerPending:rows.filter((x:any)=>x.status==='pending_manager').length,ownerPending:0,unread:0},notifications:[]});
 }
 if(action==='create_employee_request'){
   if(!STAFF_ROLES.has(role)||role==='agent')return json({error:'request_role_not_supported'},403);const type=clean(b.requestType,40);if(!REQUEST_TYPES.has(type))return json({error:'invalid_request_type'},400);const approver=await agentId();if(!approver)return json({error:'no_active_agent_for_approval'},409);const reason=clean(b.reason,2000),start=clean(b.startAt,40)||null,end=clean(b.endAt,40)||start,minutes=Math.max(0,Math.min(1440,Number(b.minutes||0)));if(!start)return json({error:'start_date_required'},400);if(type==='permission'&&minutes<=0)return json({error:'permission_minutes_required'},400);
   const ins=await db.from('employee_requests').insert({school_id:sid,requester_id:user.id,request_type:type,payload:{actorRole:role,submissionVersion:1,minutes},status:'pending_agent',current_approver:approver,supervisor_role:'agent',supervisor_user_id:approver,reason,start_at:start,end_at:end,last_note:null}).select('*').single();if(ins.error)throw ins.error;await event(db,ins.data,user.id,role,'submitted',null,{request_type:type,start_at:start,end_at:end,reason});return json({ok:true,request:ins.data});
 }
 if(action==='list_my_requests'){const r=await db.from('employee_requests').select('*').eq('school_id',sid).eq('requester_id',user.id).in('request_type',['absence','permission','leave']).order('created_at',{ascending:false});if(r.error)throw r.error;return json({ok:true,requests:r.data||[]})}
 if(action==='request_detail'){const id=clean(b.requestId,80),q=await db.from('employee_requests').select('*').eq('id',id).eq('school_id',sid).maybeSingle();if(q.error)throw q.error;if(!q.data)return json({error:'not_found'},404);const can=q.data.requester_id===user.id||(role==='agent'&&q.data.current_approver===user.id)||role==='manager';if(!can)return json({error:'forbidden'},403);const ev=await db.from('employee_request_events').select('*').eq('school_id',sid).eq('request_id',id).order('created_at');if(ev.error)throw ev.error;return json({ok:true,request:(await enrich([q.data]))[0],history:ev.data||[]})}
 if(action==='list_request_queue'){
   let q=db.from('employee_requests').select('*').eq('school_id',sid).in('request_type',['absence','permission','leave']).order('created_at');if(role==='agent')q=q.eq('status','pending_agent').eq('current_approver',user.id);else if(role==='manager')q=q.eq('status','pending_manager');else return json({ok:true,requests:[],queue:[]});const r=await q;if(r.error)throw r.error;const rows=await enrich(r.data||[]);return json({ok:true,requests:rows,queue:rows});
 }
 if(action==='resubmit_employee_request'){
   const id=clean(b.requestId,80),q=await db.from('employee_requests').select('*').eq('id',id).eq('school_id',sid).eq('requester_id',user.id).maybeSingle();if(q.error)throw q.error;if(!q.data)return json({error:'not_found'},404);if(q.data.status!=='returned_to_employee')return json({error:'request_not_returned_for_revision'},409);const type=clean(b.requestType||q.data.request_type,40);if(!REQUEST_TYPES.has(type))return json({error:'invalid_request_type'},400);const approver=await agentId();if(!approver)return json({error:'no_active_agent_for_approval'},409);const reason=clean(b.reason||q.data.reason,2000),start=clean(b.startAt||q.data.start_at,40)||null,end=clean(b.endAt||q.data.end_at,40)||start,minutes=Math.max(0,Math.min(1440,Number(b.minutes??q.data.payload?.minutes??0)));if(!start)return json({error:'start_date_required'},400);if(type==='permission'&&minutes<=0)return json({error:'permission_minutes_required'},400);const version=Number(q.data.payload?.submissionVersion||1)+1;const up=await db.from('employee_requests').update({request_type:type,reason,start_at:start,end_at:end,status:'pending_agent',current_approver:approver,supervisor_role:'agent',supervisor_user_id:approver,last_note:null,payload:{...(q.data.payload||{}),submissionVersion:version,minutes},updated_at:now()}).eq('id',id).select('*').single();if(up.error)throw up.error;await event(db,up.data,user.id,role,'resubmitted',null,{submissionVersion:version,request_type:type,start_at:start,end_at:end,reason});return json({ok:true,request:up.data});
 }
 if(action==='agent_decision'){
   if(role!=='agent')return json({error:'forbidden'},403);const id=clean(b.requestId,80),rq=await db.from('employee_requests').select('*').eq('id',id).eq('school_id',sid).maybeSingle();if(rq.error)throw rq.error;if(!rq.data)return json({error:'not_found'},404);if(rq.data.status!=='pending_agent'||rq.data.current_approver!==user.id)return json({error:'invalid_request_state'},409);const decision=clean(b.decision,30),note=clean(b.note,2000);let status='',approver:any=null,eventType='';if(decision==='approve'){approver=await managerId();if(!approver)return json({error:'no_active_manager_for_approval'},409);status='pending_manager';eventType='agent_approved'}else if(decision==='return'){if(!note)return json({error:'return_reason_required'},400);status='returned_to_employee';eventType='agent_returned'}else if(decision==='reject'){status='rejected_by_agent';eventType='agent_rejected'}else return json({error:'invalid_decision'},400);const up=await db.from('employee_requests').update({status,current_approver:approver,last_note:note||null,decided_by:user.id,decided_at:now(),updated_at:now()}).eq('id',id).select('*').single();if(up.error)throw up.error;await event(db,up.data,user.id,role,eventType,note||null,{from:'pending_agent',to:status});return json({ok:true,request:up.data});
 }
 if(action==='manager_decision'){
   if(role!=='manager')return json({error:'forbidden'},403);const id=clean(b.requestId,80),rq=await db.from('employee_requests').select('*').eq('id',id).eq('school_id',sid).maybeSingle();if(rq.error)throw rq.error;if(!rq.data)return json({error:'not_found'},404);if(rq.data.status!=='pending_manager')return json({error:'invalid_request_state'},409);const decision=clean(b.decision,30),note=clean(b.note,2000);if(!['approve','reject'].includes(decision))return json({error:'manager_decision_must_be_approve_or_reject'},400);
   if(decision==='reject'){const up=await db.from('employee_requests').update({status:'rejected_by_manager',current_approver:null,last_note:note||null,decided_by:user.id,decided_at:now(),updated_at:now()}).eq('id',id).select('*').single();if(up.error)throw up.error;await event(db,up.data,user.id,role,'manager_rejected',note||null,{from:'pending_manager',to:'rejected_by_manager'});return json({ok:true,request:up.data});}
   const movement={school_id:sid,request_id:rq.data.id,user_id:rq.data.requester_id,request_type:rq.data.request_type,movement_type:movementType(rq.data.request_type),start_at:rq.data.start_at,end_at:rq.data.end_at,minutes:Number(rq.data.payload?.minutes||0),reason:rq.data.reason||null,source:'employee_request',approved_by:user.id,approved_at:now(),payload:{requestStatus:'approved',agentApproved:true}};
   const mv=await db.from('staff_discipline_movements').upsert(movement,{onConflict:'request_id',ignoreDuplicates:false}).select('*').single();if(mv.error)throw mv.error;const up=await db.from('employee_requests').update({status:'approved',current_approver:null,last_note:note||null,decided_by:user.id,decided_at:now(),payload:{...(rq.data.payload||{}),disciplineMovementId:mv.data.id,disciplineSyncedAt:mv.data.approved_at},updated_at:now()}).eq('id',id).select('*').single();if(up.error)throw up.error;await event(db,up.data,user.id,role,'manager_approved',note||null,{from:'pending_manager',to:'approved',discipline_movement_id:mv.data.id});return json({ok:true,request:up.data,disciplineMovement:mv.data});
 }
 if(action==='list_discipline_movements'){
   let q=db.from('staff_discipline_movements').select('*').eq('school_id',sid).order('approved_at',{ascending:false});if(!['manager','agent'].includes(role))q=q.eq('user_id',user.id);const r=await q;if(r.error)throw r.error;return json({ok:true,movements:r.data||[]});
 }
 return json({error:'unsupported_action'},400);
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
