const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);console.log('PASS',msg)};
const runtime=read('private-school-runtime.js');
assert(runtime.indexOf("standalone-private-config.js")<runtime.indexOf("private-school-config.js"),'runtime loads standalone config first');
assert(runtime.includes("PrivateSchoolConfig?.supabaseUrl")&&runtime.includes("publishableKey"),'runtime validates private Supabase config');
const bridge=read('private-school-bridge.js');
assert(bridge.includes('clearSystemAdminMarkers')&&bridge.includes('clearPrivateCompat();\n    clearSystemAdminMarkers();'),'school login clears system-admin markers');
assert(!bridge.includes('localStorage.clear('),'no global localStorage.clear in private bridge');
const ownerLogin=read('private-owner-login.html');
assert(ownerLogin.includes("if(!sid)throw new Error")&&ownerLogin.includes("r.context.schoolId!==sid"),'owner login is bound to URL schoolId');
const managerLogin=read('private-manager-login.html');
assert(managerLogin.includes("if(!schoolId)throw new Error")&&managerLogin.includes("'manager'"),'manager login requires target school and manager role');
const register=read('private-manager-register.html');
assert(register.includes("invite_role!=='manager'")&&register.includes("r.status!=='pending'"),'manager registration is invite-only and stays pending');
const portal=read('private-owner-portal.html');
assert(portal.includes("create_manager_invitation")&&portal.includes("activate_manager")&&portal.includes('managerLoginPath'),'owner portal covers invite activation and login link');
const admin=read('private-system-admin.html');
assert(admin.includes("private-school-provisioning")&&admin.includes("school_overview")&&admin.includes("ownerLoginPath"),'system admin creates and resolves owner login path');
assert(admin.includes("const showLogin=()=>{$('portalView').classList.add('hidden');$('loginView').classList.remove('hidden')"),'system admin shows its own login form');
const ownerFn=read('supabase/functions/private-school-owner/index.ts');
assert(ownerFn.includes("activated_at:now")&&ownerFn.includes("activated_by:user.id"),'manager activation is audited');
assert(ownerFn.includes("disabled_at:now")&&ownerFn.includes("disabled_by:user.id"),'manager disable is audited');
assert(ownerFn.includes('manager_account_already_exists'),'duplicate manager account guarded');
const prov=read('supabase/functions/private-school-provisioning/index.ts');
for(const x of ['school_owners','school_members','school_template_profiles','ownerLoginPath','activated_at','activated_by'])assert(prov.includes(x),'provisioning contains '+x);
const invite=read('supabase/functions/private-school-invite/index.ts');
for(const x of ['invite_expired','school_not_active','status:\'pending\'','accepted_user_id','email_belongs_to_another_school'])assert(invite.includes(x),'invite contains '+x);
const cfg=read('supabase/config.toml');
assert(/\[functions\.private-school-invite\][\s\S]*?verify_jwt\s*=\s*false/.test(cfg),'manager invitation function remains anonymous-token callable');
const wf=read('.github/workflows/deploy-supabase.yml');
assert(!wf.includes('supabase db push'),'function deployment cannot mutate database schema');
assert(wf.includes('supabase functions deploy'),'function deployment remains enabled');
console.log('PHASE1_REGRESSION_CONTRACTS_OK');
