import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8'}});
const clean=(v:any)=>String(v??'').trim();
async function signedFileInfo(db:any,sid:string,fileId:any,ttl=3600){const id=clean(fileId);if(!id)return null;const f=await db.from('platform_files').select('id,bucket,object_path,display_name,original_name,mime_type,file_size').eq('id',id).eq('school_id',sid).maybeSingle();if(!f.data)return null;const u=await db.storage.from(f.data.bucket).createSignedUrl(f.data.object_path,ttl);return {...f.data,url:u.data?.signedUrl||''}}
async function templateOutput(db:any,sid:string){const t=await db.from('school_template_profiles').select('profile').eq('school_id',sid).maybeSingle();if(t.error)throw t.error;const p:any=t.data?.profile||{},o:any={...p};const pairs:any=[['ministryLogoFileId','ministry_logoUrl'],['schoolLogoFileId','school_logoUrl'],['ownerSignatureFileId','owner_signatureUrl'],['managerSignatureFileId','manager_signatureUrl'],['digitalStampFileId','digital_stampUrl']];for(const [k,u] of pairs){const f=await signedFileInfo(db,sid,p[k]||p[k.replace(/[A-Z]/g,(m:string)=>'_'+m.toLowerCase())]);o[u]=f?.url||''}return o}
async function enrichComplianceSnapshot(db:any,sid:string,snapshot:any){const out={...(snapshot||{})};const ev=Array.isArray(out.evidence)?out.evidence:[];out.evidence=await Promise.all(ev.map(async(e:any)=>{const f=await signedFileInfo(db,sid,e.file_id||e.platform_file_id);return {...e,file_id:e.file_id||e.platform_file_id,file_name:e.file_name||f?.display_name||f?.original_name||'',mime_type:f?.mime_type||'',file_size:f?.file_size||0,signed_url:f?.url||''}}));return out}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 const db=createClient(url,service,{auth:{persistSession:false}}),b=await req.json().catch(()=>({})),sid=clean(b.schoolId),action=clean(b.action);if(!sid)return json({error:'school_required'},400);
 const m=await db.from('school_members').select('role').eq('school_id',sid).eq('user_id',user.id).eq('status','active');if(m.error)throw m.error;const roles=(m.data||[]).map((x:any)=>String(x.role));if(!roles.some((r:string)=>['owner','manager'].includes(r)))return json({error:'forbidden'},403);const school=await db.from('schools').select('*').eq('id',sid).maybeSingle();if(school.error)throw school.error;if(!school.data||school.data.status!=='active')return json({error:'school_not_active'},403);
 if(action==='list'){const r=await db.from('private_school_outputs').select('*').eq('school_id',sid).order('created_at',{ascending:false});if(r.error)throw r.error;return json({ok:true,outputs:(r.data||[]).map((x:any)=>({...x,content_snapshot:x.payload||{}}))})}
 if(action==='create'){
   const snapshot=b.contentSnapshot??b.payload??{};const ins=await db.from('private_school_outputs').insert({school_id:sid,output_type:clean(b.outputType||b.sourceModule)||'institutional',title:clean(b.title)||'مخرج مؤسسي',payload:snapshot,status:'ready',created_by:user.id,source_module:clean(b.sourceModule)||null,source_record_type:clean(b.sourceRecordType)||null,source_record_id:clean(b.sourceRecordId)||null,source_version:clean(b.sourceVersion)||null,source_updated_at:b.sourceUpdatedAt||null,academic_year:clean(b.academicYear)||null,orientation:clean(b.orientation)||'auto'}).select('*').single();if(ins.error)throw ins.error;return json({ok:true,output:{...ins.data,content_snapshot:ins.data.payload||{}}})
 }
 const id=clean(b.outputId);if(!id)return json({error:'output_required'},400);const q=await db.from('private_school_outputs').select('*').eq('id',id).eq('school_id',sid).maybeSingle();if(q.error)throw q.error;if(!q.data)return json({error:'not_found'},404);
 if(action==='get'||action==='preview'){
   const t=await templateOutput(db,sid);let finalFileUrl='';if(q.data.final_file_id){const ff=await signedFileInfo(db,sid,q.data.final_file_id);finalFileUrl=ff?.url||''}
   let snapshot=q.data.payload||{};if(q.data.source_module==='private_school_compliance'||q.data.output_type==='compliance_file')snapshot=await enrichComplianceSnapshot(db,sid,snapshot);
   const output={...q.data,content_snapshot:snapshot,final_file_url:finalFileUrl};return json({ok:true,output,school:school.data,template:t,renderRules:{pageSize:'A4',orientationStrategy:'portrait-default-landscape-wide-evidence',orientation:q.data.orientation||'auto'}})
 }
 if(action==='finalize'){
   if(q.data.status==='finalized')return json({ok:true,output:{...q.data,content_snapshot:q.data.payload||{}}});const fid=clean(b.fileId)||null;if(fid){const f=await db.from('platform_files').select('id').eq('id',fid).eq('school_id',sid).maybeSingle();if(!f.data)return json({error:'invalid_final_file'},400)}const up=await db.from('private_school_outputs').update({status:'finalized',generated_page_count:Math.max(1,Number(b.pageCount||1)),final_file_id:fid,finalized_at:new Date().toISOString(),approved_by:user.id,approved_at:new Date().toISOString()}).eq('id',id).eq('school_id',sid).select('*').single();if(up.error)throw up.error;return json({ok:true,output:{...up.data,content_snapshot:up.data.payload||{}}})
 }
 if(action==='markPrinted'){const up=await db.from('private_school_outputs').update({print_count:Number(q.data.print_count||0)+1}).eq('id',id).eq('school_id',sid).select('*').single();if(up.error)throw up.error;return json({ok:true,output:{...up.data,content_snapshot:up.data.payload||{}}})}
 return json({error:'unsupported_action'},400)
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
