import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8'}});
const clean=(v:any)=>String(v??'').trim();
async function meta(db:any,id:string){try{const r=await db.auth.admin.getUserById(id);const u=r.data?.user;return {email:u?.email||'',name:u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email||'',confirmedAt:u?.email_confirmed_at||null}}catch(_){return {email:'',name:'',confirmedAt:null}}}
async function adminGuard(req:Request){const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return {error:json({error:'unauthorized'},401)};const db=createClient(url,service,{auth:{persistSession:false}});const a=await db.from('system_admins').select('user_id,email,is_active').eq('user_id',user.id).eq('is_active',true).maybeSingle();if(a.error||!a.data)return {error:json({error:'forbidden'},403)};return {db,user}}
async function ownerForSchool(db:any,schoolId:string){const mq=await db.from('school_members').select('id,user_id,role,status,display_name,created_at').eq('school_id',schoolId).eq('role','owner').order('created_at',{ascending:true});if(mq.error)throw mq.error;const oq=await db.from('school_owners').select('user_id,is_primary,created_at').eq('school_id',schoolId);if(oq.error)throw oq.error;const primaryMap=new Map<string,any>((oq.data||[]).map((o:any)=>[String(o.user_id),o]));const rows=[];const seen=new Set<string>();for(const m of mq.data||[]){const u=await meta(db,m.user_id);rows.push({membershipId:m.id,userId:m.user_id,role:'owner',status:m.status,displayName:m.display_name,isPrimary:!!primaryMap.get(m.user_id)?.is_primary,...u});seen.add(m.user_id)}for(const o of oq.data||[]){if(seen.has(o.user_id))continue;const u=await meta(db,o.user_id);rows.push({userId:o.user_id,role:'owner',status:'active',isPrimary:!!o.is_primary,...u})}return rows}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const g=await adminGuard(req);if(g.error)return g.error;const db:any=g.db,user:any=g.user;const b=await req.json().catch(()=>({}));const action=clean(b.action||'verify');
if(action==='verify')return json({ok:true,user:{id:user.id,email:user.email}});
if(action==='list_schools'){const r=await db.from('schools').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;const schools=[];for(const s of r.data||[]){const owners=await ownerForSchool(db,s.id);const owner=owners.find((x:any)=>x.isPrimary)||owners[0]||null;schools.push({...s,owner,ownerLoginPath:owner?`private-owner-login.html?schoolId=${encodeURIComponent(s.id)}`:''})}return json({ok:true,schools})}
if(action==='school_overview'){const sid=clean(b.schoolId);const s=await db.from('schools').select('*').eq('id',sid).maybeSingle();if(s.error)throw s.error;if(!s.data)return json({error:'school_not_found'},404);const owners=await ownerForSchool(db,sid);const mq=await db.from('school_members').select('*').eq('school_id',sid).order('created_at',{ascending:true});if(mq.error)throw mq.error;const members=[];for(const m of mq.data||[]){const u=await meta(db,m.user_id);members.push({...m,...u})}const iq=await db.from('school_invites').select('*').eq('school_id',sid).order('created_at',{ascending:false});if(iq.error)throw iq.error;return json({ok:true,school:s.data,owners,members,invitations:iq.data||[],ownerLoginPath:owners.length?`private-owner-login.html?schoolId=${encodeURIComponent(sid)}`:''})}
if(action==='role_directory'){const requested=clean(b.role),allowed=['owner','manager','agent','teacher','student_advisor','health_advisor','activity_leader','kindergarten_teacher','administrative_employee'];if(!allowed.includes(requested))return json({error:'invalid_role'},400);const sq=await db.from('schools').select('id,school_code,school_name,status').order('created_at',{ascending:false});if(sq.error)throw sq.error;const out=[];for(const s of sq.data||[]){if(requested==='owner'){const owners=await ownerForSchool(db,s.id);for(const o of owners)out.push({school:s,...o,status:o.status||(s.status==='active'?'active':s.status),loginPath:`private-owner-login.html?schoolId=${encodeURIComponent(s.id)}`})}else{const q=await db.from('school_members').select('id,user_id,role,status,display_name,created_at').eq('school_id',s.id).eq('role',requested);if(q.error)throw q.error;for(const m of q.data||[]){const u=await meta(db,m.user_id);out.push({school:s,membershipId:m.id,userId:m.user_id,role:m.role,status:m.status,displayName:m.display_name,...u})}}}return json({ok:true,role:requested,entries:out,schoolCount:(sq.data||[]).length,activeSchoolCount:(sq.data||[]).filter((x:any)=>x.status==='active').length})}
if(action==='update_school'){const sid=clean(b.schoolId),name=clean(b.schoolName);if(!sid||!name)return json({error:'invalid_input'},400);const r=await db.from('schools').update({school_name:name,updated_at:new Date().toISOString()}).eq('id',sid).select('*').single();if(r.error)throw r.error;return json({ok:true,school:r.data})}
if(action==='update_owner'){const sid=clean(b.schoolId),uid=clean(b.ownerUserId),email=clean(b.email).toLowerCase(),name=clean(b.name);if(!sid||!uid||!email.includes('@'))return json({error:'invalid_input'},400);const owners=await ownerForSchool(db,sid);if(!owners.some((x:any)=>x.userId===uid))return json({error:'owner_not_found'},404);const current=await db.auth.admin.getUserById(uid);if(current.error)throw current.error;const upd=await db.auth.admin.updateUserById(uid,{email,email_confirm:true,user_metadata:{...(current.data.user.user_metadata||{}),full_name:name||current.data.user.user_metadata?.full_name||email,role:'owner'}});if(upd.error)throw upd.error;await db.from('school_members').update({display_name:name||null}).eq('school_id',sid).eq('user_id',uid).eq('role','owner');return json({ok:true,owner:{userId:uid,email:upd.data.user.email,name:upd.data.user.user_metadata?.full_name||''}})}
if(action==='reset_owner_password'){const sid=clean(b.schoolId),uid=clean(b.ownerUserId),password=String(b.password||'');if(!sid||!uid||password.length<8)return json({error:'invalid_input'},400);const owners=await ownerForSchool(db,sid);if(!owners.some((x:any)=>x.userId===uid))return json({error:'owner_not_found'},404);const r=await db.auth.admin.updateUserById(uid,{password});if(r.error)throw r.error;return json({ok:true})}
if(action==='set_school_status'){const id=clean(b.schoolId),status=clean(b.status);if(!id||!['active','disabled','archived'].includes(status))return json({error:'invalid_input'},400);const patch:any={status,updated_at:new Date().toISOString()};if(status==='disabled'){patch.disabled_at=new Date().toISOString();patch.disabled_by=user.id}else if(status==='active'){patch.disabled_at=null;patch.disabled_by=null}const r=await db.from('schools').update(patch).eq('id',id).select('*').single();if(r.error)throw r.error;return json({ok:true,school:r.data})}
if(action==='delete_school'){if(clean(b.confirmText)!=='DELETE')return json({error:'confirmation_required'},400);const id=clean(b.schoolId);if(!id)return json({error:'school_required'},400);const users=await db.from('school_members').select('user_id').eq('school_id',id);if(users.error)throw users.error;const ids=[...new Set((users.data||[]).map((x:any)=>x.user_id))];const del=await db.from('schools').delete().eq('id',id);if(del.error)throw del.error;for(const uid of ids){const rem=await db.from('school_members').select('id',{count:'exact',head:true}).eq('user_id',uid);const own=await db.from('school_owners').select('id',{count:'exact',head:true}).eq('user_id',uid);if((rem.count||0)===0&&(own.count||0)===0){try{await db.auth.admin.deleteUser(uid)}catch(_){}}}return json({ok:true,deletedSchoolId:id})}
return json({error:'unsupported_action'},400)}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
