import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8'}});const clean=(v:any)=>String(v??'').trim();const code=()=>`PRV-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
async function findUserByEmail(db:any,email:string){for(let page=1;page<=20;page++){const r=await db.auth.admin.listUsers({page,perPage:100});if(r.error)throw r.error;const f=(r.data?.users||[]).find((x:any)=>String(x.email||'').toLowerCase()===email.toLowerCase());if(f)return f;if((r.data?.users||[]).length<100)break}return null}
async function userMeta(db:any,uid:string){try{const r=await db.auth.admin.getUserById(uid);const u=r.data?.user;return {email:u?.email||'',name:String(u?.user_metadata?.full_name||u?.user_metadata?.name||''),confirmed:!!u?.email_confirmed_at}}catch(_){return {email:'',name:'',confirmed:false}}}
async function ownersForSchool(db:any,sid:string){const [oq,mq]=await Promise.all([db.from('school_owners').select('*').eq('school_id',sid).order('is_primary',{ascending:false}),db.from('school_members').select('*').eq('school_id',sid).eq('role','owner').order('created_at',{ascending:true})]);if(oq.error)throw oq.error;if(mq.error)throw mq.error;const ownMap=new Map((oq.data||[]).map((o:any)=>[o.user_id,o]));const out=[];const seen=new Set<string>();for(const m of mq.data||[]){const u=await userMeta(db,m.user_id);const o:any=ownMap.get(m.user_id)||{};out.push({...o,membership_id:m.id,user_id:m.user_id,status:m.status,display_name:m.display_name,is_primary:!!o.is_primary,...u});seen.add(m.user_id)}for(const o of oq.data||[]){if(seen.has(o.user_id))continue;out.push({...o,status:'active',...(await userMeta(db,o.user_id))})}return out}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('authorization')||''}}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);const db=createClient(url,service,{auth:{persistSession:false}});const sa=await db.from('system_admins').select('user_id').eq('user_id',user.id).eq('is_active',true).maybeSingle();if(!sa.data)return json({error:'forbidden'},403);
 const b=await req.json().catch(()=>({})),action=clean(b.action||'create');if(action==='overview'){const sid=clean(b.schoolId);if(!sid)return json({error:'school_required'},400);const [school,members,invitations]=await Promise.all([db.from('schools').select('*').eq('id',sid).maybeSingle(),db.from('school_members').select('*').eq('school_id',sid),db.from('school_invites').select('*').eq('school_id',sid).order('created_at',{ascending:false})]);if(school.error)throw school.error;if(!school.data)return json({error:'school_not_found'},404);if(members.error||invitations.error)throw members.error||invitations.error;const owners=await ownersForSchool(db,sid),ownerLoginPath=owners.some((x:any)=>x.status==='active')?`private-owner-login.html?schoolId=${encodeURIComponent(sid)}`:'';return json({ok:true,school:school.data,owners,members:members.data||[],invitations:invitations.data||[],ownerLoginPath,ownerLoginUrl:ownerLoginPath})}
 const schoolName=clean(b.schoolName),ownerName=clean(b.ownerName),ownerEmail=clean(b.ownerEmail).toLowerCase(),password=String(b.password||'');if(!schoolName||!ownerName||!ownerEmail.includes('@')||password.length<8)return json({error:'invalid_input'},400);
 const existing=await findUserByEmail(db,ownerEmail);if(existing){const ms=await db.from('school_members').select('school_id,role,status').eq('user_id',existing.id);const os=await db.from('school_owners').select('school_id').eq('user_id',existing.id);if(ms.error||os.error)throw ms.error||os.error;return json({error:'owner_email_already_registered',existingMemberships:ms.data||[],existingOwnerships:os.data||[]},409)}
 let authUserId='',schoolId='';try{const created=await db.auth.admin.createUser({email:ownerEmail,password,email_confirm:true,user_metadata:{full_name:ownerName,role:'owner'}});if(created.error)throw created.error;authUserId=created.data.user.id;const school=await db.from('schools').insert({school_code:code(),school_name:schoolName,school_type:'private',status:'active'}).select('*').single();if(school.error)throw school.error;schoolId=school.data.id;const o=await db.from('school_owners').insert({school_id:schoolId,user_id:authUserId,is_primary:true});if(o.error)throw o.error;const m=await db.from('school_members').insert({school_id:schoolId,user_id:authUserId,role:'owner',status:'active',display_name:ownerName,activated_at:new Date().toISOString(),activated_by:user.id,invited_by:user.id});if(m.error)throw m.error;const tp=await db.from('school_template_profiles').insert({school_id:schoolId,profile:{schoolDisplayName:schoolName,ownerDisplayName:ownerName},updated_by:authUserId});if(tp.error)throw tp.error;const ownerLoginPath=`private-owner-login.html?schoolId=${encodeURIComponent(schoolId)}`;return json({ok:true,school:school.data,owner:{userId:authUserId,email:ownerEmail,name:ownerName,confirmed:true,status:'active'},ownerLoginPath,ownerLoginUrl:ownerLoginPath})}catch(e){if(schoolId)await db.from('schools').delete().eq('id',schoolId);if(authUserId){try{await db.auth.admin.deleteUser(authUserId)}catch(_){}}throw e}
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
